@startuml

header Chat
title Схема БД

hide circle
'skinparam linetype ortho




entity chat{
    * **chat_id**: int
}

entity user{
    * **user_id**: int
    * **username**: text
    * **password**: text
    * **email**: text
}

entity chat_user{
    * **chat_id**: int FK
    * **user_id**: int FK
    * **status_id**: int FK
    * **changed**: text
}

entity messages{
    * **message_id**: int PK
    * **user_id**: int FK
    * **chat_id**: int FK
    message_text: text
    **created**: text
}


entity statuses{
    * **status_id**: int PK
    * **status_name**: varchar

}

messages }o--|| user
chat_user }o--|| user
chat ||--o{ chat_user
chat_user }o--||statuses
messages}o--||chat

@enduml

